### ISSUE TITLE
🐞[Bug] - docker-compose 에러 수정

### ISSUE THREAD

**Issue by mushroom1324** [CEOS-Developers/CEOS-BE#171]
# 🐞 Bug - docker-compose 에러 수정

### 🕵️‍♀️ Condition
Github Actions 에서 docker-compose시 에러 발생

---

에러 발생 조건 및 대상

### 📝 Description

docker-compose.yml 파일이 수정되지 않아서 발생한 버그
기존 코드:
```
version: "3"

services:
  backend:
    image: ceos17/ceos-backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
```

수정된 코드:
```
version: "3"

services:
  backend:
    image: ceos17/ceos-backend
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    image: ceos17/ceos-nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
```

---

- github에서 파일을 clone 하지 않으므로 이미지만 가져와서 컨테이너를 띄울 수 있도록 수정

### ✅ To Do List 

---

- [x] docker-compose.yml 수정
